apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  labels:
    app: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: app
          image: e-commerce-backend:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: NEST_APP
              value: user-service
          envFrom:
            - configMapRef:
                name: e-commerce-config
            - secretRef:
                name: e-commerce-secrets
